
stages:
  - build
  - test

build_image:
  stage: build
  script:
    - docker build -t rzdselenide:1.0 .
  tags:
    - docker

run_tests:
  stage: test
  script:
    - docker run --shm-size=2g rzdselenide:1.0
  tags:
    - docker
